# Generated by pip2nix 0.7.0.dev1
# See https://github.com/johbo/pip2nix

{ pkgs, fetchurl, fetchgit }:

self: super: {
  trytond-account = super.buildPythonPackage {
    name = "trytond-account-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-dateutil python-sql simpleeval trytond-company trytond-currency trytond-party trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/43/16/22ab6c5206f833b3e3358efdcac8dea5efd369df2f4bbd45fda603a14e52/trytond_account-4.2.0.tar.gz";
      sha256 = "1611qa5hbrplqf7gvjpss283d76glflihk7ybpiqsgamkx4hfxmr";
    };
  };
  trytond-account-asset = super.buildPythonPackage {
    name = "trytond-account-asset-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [cached-property python-dateutil trytond-account trytond-account-product trytond-product trytond-account-invoice trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/48/f2/1a6abd8465887b85ea2f2c8670e87c87a4afd5ac8da8599d92707948a20e/trytond_account_asset-4.2.0.tar.gz";
      sha256 = "1igbmb1zbkcd0ynyvz1isyk0fv603qw133cwgzmzf5g5k107ziwa";
    };
  };
  trytond-account-be = super.buildPythonPackage {
    name = "trytond-account-be-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-account trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/61/e6/c135443432f509a5e3e05d01fd6459879d6f00b2313afa0dde305f353c1d/trytond_account_be-4.2.0.tar.gz";
      sha256 = "0xxf5ir1bk0h17ljzbpiyacv081rr80lzf2kdmrvagrhs7izgad9";
    };
  };
  trytond-account-credit-limit = super.buildPythonPackage {
    name = "trytond-account-credit-limit-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-account trytond-company trytond-party trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/8e/c1/266f77150516bdcd20e7b995f1c79e7bfd52e7002a9d1b0206b22149bd06/trytond_account_credit_limit-4.2.0.tar.gz";
      sha256 = "1hvqf9wqf3ihkjkp2nn2s8bbpmkgi7ly2qkgrqil1wcjxqmw48ld";
    };
  };
  trytond-account-de-skr03 = super.buildPythonPackage {
    name = "trytond-account-de-skr03-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-account trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/31/d3/e87a82c92441b3dc8ee8857b01c83285442507fee868109a86b61416a193/trytond_account_de_skr03-4.2.0.tar.gz";
      sha256 = "0m84gnz99vcrf5j702i7vwb0h2m5b0i5c0kd7ffy000wb5yb0zws";
    };
  };
  trytond-account-deposit = super.buildPythonPackage {
    name = "trytond-account-deposit-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-dateutil python-sql trytond-account trytond-account-invoice trytond-company trytond-party trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/6c/f8/8e4b7c8aef442da31db7d70efece2358649586c07c99b7a8ab595698955f/trytond_account_deposit-4.2.0.tar.gz";
      sha256 = "0sn673pgzpbmivh5z23d5hzp59ayrramnr6c5xhim7a3rkdnzv7k";
    };
  };
  trytond-account-dunning = super.buildPythonPackage {
    name = "trytond-account-dunning-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-sql trytond-account trytond-company trytond-party trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/59/57/439838859228ab8c23f8d943948b538b38fd5943114cb53fa6d34ded2a89/trytond_account_dunning-4.2.0.tar.gz";
      sha256 = "1iphwnkxrlxq3g4y5v60q84da7k4mrccarcmqdz4j8g8kzlcv5x6";
    };
  };
  trytond-account-dunning-fee = super.buildPythonPackage {
    name = "trytond-account-dunning-fee-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-account-dunning trytond-account-product trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/d9/a8/926df7bedfec921ffea5edda7792cbec8f0a95cf34c134f78103c3fbf29e/trytond_account_dunning_fee-4.2.0.tar.gz";
      sha256 = "03jzqxvhgcdhxhj6sn3svvc64hhvqvcc521cdqv3wa2b2rqgkdix";
    };
  };
  trytond-account-dunning-letter = super.buildPythonPackage {
    name = "trytond-account-dunning-letter-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-account trytond-account-dunning trytond-company trytond-party trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/77/be/bf96a87b1d0e8193c31959fa55fd6c830b4cfa1a1c360d9d04f2e3b0b198/trytond_account_dunning_letter-4.2.0.tar.gz";
      sha256 = "1jahz1z647la6cc7xyhwn1s17fylq2zcf5licxvgdsdkjgajwkn8";
    };
  };
  trytond-account-fr = super.buildPythonPackage {
    name = "trytond-account-fr-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-account trytond-party-siret trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/8a/6b/d276ec217138f3492de2d9b8835cd82682acbb1998bca03967e403059e8d/trytond_account_fr-4.2.0.tar.gz";
      sha256 = "1550872crykzz9iq1a9qr3fk4wxp01rgrkr6d55dkjq9w151nsxv";
    };
  };
  trytond-account-invoice = super.buildPythonPackage {
    name = "trytond-account-invoice-4.2.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-dateutil python-sql trytond-account trytond-account-product trytond-company trytond-currency trytond-party trytond-product trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/54/e7/b2d3d1b6aeb621e8e7b3cc629a33094190f3b97b7d8f373d803db2d6bd00/trytond_account_invoice-4.2.1.tar.gz";
      sha256 = "01gmh7l2gig63r1nwlzfl7793zp9h1hlphlsbmnr8d3zrx5c9l08";
    };
  };
  trytond-account-invoice-history = super.buildPythonPackage {
    name = "trytond-account-invoice-history-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-account-invoice trytond-party trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/8b/d8/eea1f8b483c1a20629fbb95d148b9b9863ac45620c884a74aad95e8f7105/trytond_account_invoice_history-4.2.0.tar.gz";
      sha256 = "0alrjs3az2yjsncj6ljdj64gj8zcss5sk3gr2gjx81cg134hzz6l";
    };
  };
  trytond-account-invoice-line-standalone = super.buildPythonPackage {
    name = "trytond-account-invoice-line-standalone-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-account-invoice trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/4f/ce/6d27cdde45e28542081a824c6f9fe79a04873c06b1bd1f548c5293486285/trytond_account_invoice_line_standalone-4.2.0.tar.gz";
      sha256 = "1m5lrkqmlbbsbf2dj2hcpxdjjxly0sk1qkfk5b4qflfnyhx7mi9w";
    };
  };
  trytond-account-invoice-stock = super.buildPythonPackage {
    name = "trytond-account-invoice-stock-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-account-invoice trytond-stock trytond-product trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/92/ab/9a2e030897c615a3eb6b9b072fc9f2bee1c2f20b43e0f40b849cf7a8c833/trytond_account_invoice_stock-4.2.0.tar.gz";
      sha256 = "0cp2hdaxdydh505lckqcglimy2j5zkpagl83clzl7j93jzmj5ij6";
    };
  };
  trytond-account-payment = super.buildPythonPackage {
    name = "trytond-account-payment-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-sql trytond-account trytond-company trytond-currency trytond-party trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/f8/ab/012196c3366b405422c84b3afee103d6dba80802b8a3ddae24bc33c8b0db/trytond_account_payment-4.2.0.tar.gz";
      sha256 = "0b1cpkrvkd979zl66r901p6b9wgdjyznbjw7krw8q3h61bpxnp2g";
    };
  };
  trytond-account-payment-clearing = super.buildPythonPackage {
    name = "trytond-account-payment-clearing-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-account-payment trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/f5/9a/979ced1932aabe23da5b80794dd75bd7df450be74de330519edd018de122/trytond_account_payment_clearing-4.2.0.tar.gz";
      sha256 = "0g41kqrviadm7zc39sf05bwz0489wrzk3zxflx5wpa86kamdpbll";
    };
  };
  trytond-account-payment-sepa = super.buildPythonPackage {
    name = "trytond-account-payment-sepa-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [Genshi lxml python-dateutil python-stdnum trytond-account-payment trytond-company trytond-bank trytond-party trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/09/18/6abec9394dd0c328a3876a693618b9e3f2618e4675af2960112577cef946/trytond_account_payment_sepa-4.2.0.tar.gz";
      sha256 = "1c270nrk45g67rlrl2h6i5pyv3fpgpj1728x3q5wl7v7i2c8kcy6";
    };
  };
  trytond-account-payment-sepa-cfonb = super.buildPythonPackage {
    name = "trytond-account-payment-sepa-cfonb-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [Genshi lxml trytond-account-payment trytond-account-payment-sepa trytond-company trytond-bank trytond-party trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/96/3b/3ed43257df3b72bdcf3e153756c9a9d2105e987a56951b68a3c50bd6b95d/trytond_account_payment_sepa_cfonb-4.2.0.tar.gz";
      sha256 = "0djsga7jf61kbn8vvf1xdmfhmrm4al9s0yzzf5sw7mil0x2jrp58";
    };
  };
  trytond-account-product = super.buildPythonPackage {
    name = "trytond-account-product-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-account trytond-company trytond-product trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/d3/6c/58569874d4801e49ea1c21ff967941c35afcebf2570e41bbb39405156def/trytond_account_product-4.2.0.tar.gz";
      sha256 = "01vbw9nls6mx53agdqyp7vws49pl9c8k2gni1z5zsmjadxwgn8vs";
    };
  };
  trytond-account-statement = super.buildPythonPackage {
    name = "trytond-account-statement-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-sql trytond-account trytond-account-invoice trytond-company trytond-currency trytond-party trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/90/2d/d8ff7e97544dad2317d62f6c8296b6ac6112d04dd6b7ffa564f29381b412/trytond_account_statement-4.2.0.tar.gz";
      sha256 = "1maiq63qp2s5wygwig7l9g2y61pgj6xhn5jhid8s2vgx6acd2pka";
    };
  };
  trytond-account-stock-anglo-saxon = super.buildPythonPackage {
    name = "trytond-account-stock-anglo-saxon-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-account trytond-account-invoice trytond-account-product trytond-account-stock-continental trytond-purchase trytond-sale trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/86/71/07314bf92d86d7c8b47bbe5831be0c7b0fee3220ccad856485d81837e2c8/trytond_account_stock_anglo_saxon-4.2.0.tar.gz";
      sha256 = "00fc8ps5rs10b8bpgcwwxdgnbm7x2nvll147qmkd3gq2rk1g7193";
    };
  };
  trytond-account-stock-continental = super.buildPythonPackage {
    name = "trytond-account-stock-continental-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-account trytond-account-product trytond-stock trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/8a/38/d328c67fa31623df9a599266685dc2382fbed5960d2837a58372f6bbc8b6/trytond_account_stock_continental-4.2.0.tar.gz";
      sha256 = "0p847vqwxqh66nw7j6h0i42ncpg9yfpmcvacc8b6lcwk6fijj4q5";
    };
  };
  trytond-account-stock-landed-cost = super.buildPythonPackage {
    name = "trytond-account-stock-landed-cost-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-account trytond-account-invoice trytond-product trytond-stock trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/c2/a5/99e587b69765af056329f61362c534e1f4f44496178898304067bb60575c/trytond_account_stock_landed_cost-4.2.0.tar.gz";
      sha256 = "0capjns7mzwjlqqpawd2bw9k1g2vxvh08zil2fmxd9apicq1hd3i";
    };
  };
  trytond-account-stock-landed-cost-weight = super.buildPythonPackage {
    name = "trytond-account-stock-landed-cost-weight-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-account-stock-landed-cost trytond-product trytond-product-measurements trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/d1/55/1e336c8f2e3308af9c9e62f0863e2b2cf94e11a35d1e068bed900c879873/trytond_account_stock_landed_cost_weight-4.2.0.tar.gz";
      sha256 = "05j6y59g89wxxwjlwwgwdsx1z0sdgln010pd7c5ny14waglj87f2";
    };
  };
  trytond-account-tax-rule-country = super.buildPythonPackage {
    name = "trytond-account-tax-rule-country-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-account trytond-country trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/33/5f/6fb34cfe261cdbd8b55d396dfe2f9889ec85811e35e293f07057b54e183a/trytond_account_tax_rule_country-4.2.0.tar.gz";
      sha256 = "1qpxrw9w554zh7ichvrxx00grkpvm76y0grch8hmg7pmzay0f6zy";
    };
  };
  trytond-analytic-account = super.buildPythonPackage {
    name = "trytond-analytic-account-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-sql trytond-account trytond-company trytond-currency trytond-party trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/c5/4e/86fd12185070fcd7f135964390705d20e0ebe142cd8c55af2d460c39113f/trytond_analytic_account-4.2.0.tar.gz";
      sha256 = "1qkkv1vshjdhsxlgpjjfkv8n9mmmi5m5ihvfx5ha75994yichz3f";
    };
  };
  trytond-analytic-invoice = super.buildPythonPackage {
    name = "trytond-analytic-invoice-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-account-invoice trytond-analytic-account trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/36/b9/3a7c54680c3e048b2db9fefab24c60cc4716d0fa89c443e53ac731c06ea2/trytond_analytic_invoice-4.2.0.tar.gz";
      sha256 = "1cb1fdcrxi5g3lhvfajxzk1w49niczpq7dvkkb3w3dnbqkn5gbpm";
    };
  };
  trytond-analytic-purchase = super.buildPythonPackage {
    name = "trytond-analytic-purchase-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-analytic-account trytond-analytic-invoice trytond-purchase trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/fa/87/2877a8823290eedea2ed88a82171fdf026508ff82f91162801433c8484a0/trytond_analytic_purchase-4.2.0.tar.gz";
      sha256 = "0j4xyk5gjas0vmy9fhbmp25vpcnrm7z713grn8q2m6zs6cz5dnqp";
    };
  };
  trytond-analytic-sale = super.buildPythonPackage {
    name = "trytond-analytic-sale-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-analytic-account trytond-analytic-invoice trytond-sale trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/11/4f/55ab48132de06d75ef4c4ec98ffea188dbe9b34bba2085cac0f3437da8b8/trytond_analytic_sale-4.2.0.tar.gz";
      sha256 = "0r43kfzqzjh2c6lilgwv7kspwg8dgm3dqnvnsb5k7cdzfpq90fr6";
    };
  };
  trytond-authentication-sms = super.buildPythonPackage {
    name = "trytond-authentication-sms-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/f7/94/6f8a7deb75f178ba0f34eb9d4e6ed18df76da3314aa8224dc931e2f8c27d/trytond_authentication_sms-4.2.0.tar.gz";
      sha256 = "1rjr6vmzxyr4vr9c6z2kmj9jjkbzwzsvk00by5z92s2a6ips563a";
    };
  };
  trytond-bank = super.buildPythonPackage {
    name = "trytond-bank-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-stdnum python-sql trytond-party trytond-currency trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/96/c4/e1a773f65077a8d0a70d7ed7b3f136ede4de146fb24d6db0cd69f8761f85/trytond_bank-4.2.0.tar.gz";
      sha256 = "05zv551nvyy37vcqn993vpjwdfg8lmvg0lrh8hqxj2a9wayhf060";
    };
  };
  trytond-calendar = super.buildPythonPackage {
    name = "trytond-calendar-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [vobject PyWebDAV python-dateutil pytz python-sql trytond-webdav trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/04/33/049712ada1d5e10e20ef7004709975921082602336cbac0ecb7c409e766c/trytond_calendar-4.2.0.tar.gz";
      sha256 = "1ab64bhx13mvjx0cwl8vw4i35jr420b7c2pnn5v7cfbi668f23hh";
    };
  };
  trytond-calendar-classification = super.buildPythonPackage {
    name = "trytond-calendar-classification-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [vobject trytond-calendar trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/43/df/683e08379d94cdb4573a7c0996704fe5fd5d65103d3bdac7b206c4cc1fe3/trytond_calendar_classification-4.2.0.tar.gz";
      sha256 = "05pamqzbxnv61p06yhr58ksqwqlkj0np3rb0gwkljbw26c5fjiyw";
    };
  };
  trytond-calendar-scheduling = super.buildPythonPackage {
    name = "trytond-calendar-scheduling-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [PyWebDAV python-dateutil trytond-calendar trytond-webdav trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/c6/87/45d4f3563f94df612c6b89b31649b89793ce7c7ff84aa764934c50187ba9/trytond_calendar_scheduling-4.2.0.tar.gz";
      sha256 = "01dn7xj39ycmsnwi5i9vp0z0ycaa4ffckf40pnv88g2v3p4ahggf";
    };
  };
  trytond-calendar-todo = super.buildPythonPackage {
    name = "trytond-calendar-todo-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [vobject PyWebDAV python-dateutil pytz python-sql trytond-calendar trytond-webdav trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/4e/ca/d0550de74eb1e3f1ddc0127606417e1b79ccbeff0d3239a238f729e9c5e9/trytond_calendar_todo-4.2.0.tar.gz";
      sha256 = "0c26fj9n9g9z7glgf35j57f4c7lq0vrpkxap2c5k1ayy3mj06wzd";
    };
  };
  trytond-carrier = super.buildPythonPackage {
    name = "trytond-carrier-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-country trytond-party trytond-product trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/52/ed/7a93f595dc047e238aba456bab6db5ce8a647e3744e1bff4f5f2de627c77/trytond_carrier-4.2.0.tar.gz";
      sha256 = "1ifg2b51f550azkzqxckgni89xrc8ljdyq4mk7vjwf2fg7q0f8rq";
    };
  };
  trytond-carrier-percentage = super.buildPythonPackage {
    name = "trytond-carrier-percentage-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-carrier trytond-currency trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/6f/86/a218af1959b58ffac84ca95de33882d009aed3809e0bf409a67657b42e19/trytond_carrier_percentage-4.2.0.tar.gz";
      sha256 = "04384am567yrjrs5l3c63iqvmyhsyzv3yc32ispkbi921amrij6k";
    };
  };
  trytond-carrier-weight = super.buildPythonPackage {
    name = "trytond-carrier-weight-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-carrier trytond-company trytond-currency trytond-product trytond-product-measurements trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/e0/a0/f0fd6c50f88be8c4e6e227efc53666eb2ed1268600d5936670ecf7666b7c/trytond_carrier_weight-4.2.0.tar.gz";
      sha256 = "17ryajh8cnxr8vbkbpkkhvjp7l330syphin5n6z63b2ssw0l154d";
    };
  };
  trytond-commission = super.buildPythonPackage {
    name = "trytond-commission-4.2.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [simpleeval python-sql trytond-account trytond-account-invoice trytond-account-product trytond-party trytond-product trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/b0/bd/bea63dc09e26557a2add4ae7f561a1359707986cbbbc6066459ae208e39a/trytond_commission-4.2.1.tar.gz";
      sha256 = "02x1bj155bwrqj6vyfa6l5yk1f9yncxkynph9vz6lqw2brag9fmh";
    };
  };
  trytond-commission-waiting = super.buildPythonPackage {
    name = "trytond-commission-waiting-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-account trytond-account-invoice trytond-commission trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/bc/4b/aa97d80b00386a32c2c9353a61b3baecd00ad6a3b8eb5f5aae051093e544/trytond_commission_waiting-4.2.0.tar.gz";
      sha256 = "185qnb3rkah7vcij0mh16nvz5ds2x2ka8fk3vyjhj683a3mh5fmk";
    };
  };
  trytond-company = super.buildPythonPackage {
    name = "trytond-company-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-currency trytond-party trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/20/a6/1580d8a0ddd9a9c03bc48f5a123365c10f9934989c0be7015003f3e5a98e/trytond_company-4.2.0.tar.gz";
      sha256 = "04a0601y5rfgnivsml5crxmqr3af3k5lb50c728s5y9dmp2pzkq8";
    };
  };
  trytond-company-work-time = super.buildPythonPackage {
    name = "trytond-company-work-time-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-company trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/86/c9/d5a97bf739c8d7533ac5f2bcefdcb601da41a78a54543ba418b2f6c326c1/trytond_company_work_time-4.2.0.tar.gz";
      sha256 = "05nm4qhpaysjgd1d7wr87jkbx40iavsk399brfilb6ix1z3nkai4";
    };
  };
  trytond-country = super.buildPythonPackage {
    name = "trytond-country-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/05/b3/cbdccb60bd8a8c3c290f0b5fd75b36005275e44e109bc745f57aa479c0b3/trytond_country-4.2.0.tar.gz";
      sha256 = "191lgrp6gh8a2bfksvsq3kvsb7s8mv0a29i22njgh6rnvgqm5n3j";
    };
  };
  trytond-currency = super.buildPythonPackage {
    name = "trytond-currency-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/14/b2/b636a2644d3f3401e6ec8e1618e2f669f3239d55359dacea7802df8ffbd1/trytond_currency-4.2.0.tar.gz";
      sha256 = "1n90p3rhgjwa14hf4zcw9z4yh7vmv338wchqbbiy0555h52ar8wa";
    };
  };
  trytond-customs = super.buildPythonPackage {
    name = "trytond-customs-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [simpleeval python-sql trytond-country trytond-currency trytond-product trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/d7/fa/bef130131aed6a49704d039694aab9ab0c973611b3180fd7f1ef6707a77b/trytond_customs-4.2.0.tar.gz";
      sha256 = "0af8wry96js796hvy85av40y2ybhi18nq2kw0b68d2b4i2cz1fan";
    };
  };
  trytond-dashboard = super.buildPythonPackage {
    name = "trytond-dashboard-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [lxml python-sql trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/42/38/b1a696b9366d1ed395cb8edbddc3ab6911fac57cb6f3297f2b5ee44e4c94/trytond_dashboard-4.2.0.tar.gz";
      sha256 = "05bh7nkjxwb7gdxqqqmb2i142v6jjcp5vl93vkgfnggpa8z7acyq";
    };
  };
  trytond-google-maps = super.buildPythonPackage {
    name = "trytond-google-maps-4.2.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-party trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/91/b3/7ccbe3b16d576e7cad63d58e84e7593c062625ccc35b3dba88fbba75e4e1/trytond_google_maps-4.2.1.tar.gz";
      sha256 = "03pb22hcql5lmmqmwq8zcaik9mbh3h5qmyd59wzwykijzi6vdagq";
    };
  };
  trytond-ldap-authentication = super.buildPythonPackage {
    name = "trytond-ldap-authentication-4.2.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [ldap3 trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/db/b0/3acc0e9ec9afbfe3243dd462ade94c35346d85c5b5385fe1fdb9302245eb/trytond_ldap_authentication-4.2.1.tar.gz";
      sha256 = "1lg4j3a5a40qsvjbj9wmimv9zdq6jzr6hjk8fwzhv99mxx9iwbgl";
    };
  };
  trytond-ldap-connection = super.buildPythonPackage {
    name = "trytond-ldap-connection-3.2.2";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-ldap trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/e1/78/97e59c9ea5e6517d40928600a7a815a6ee268ffd6891104e4e29b355d27d/trytond_ldap_connection-3.2.2.tar.gz";
      sha256 = "00bb78bb2k89cp39rl6lfk8k7q99kqgivaj243508110n4m7568m";
    };
  };
  trytond-party = super.buildPythonPackage {
    name = "trytond-party-4.2.2";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-sql python-stdnum trytond-country trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/d4/f9/d27d9373f5aaeeb27ea1b45a8c17514a479c99fe73630a53260338fb2c20/trytond_party-4.2.2.tar.gz";
      sha256 = "04vnwp2r9g4y18cwmk1jpkkrj4pmwwca0j0q54yxxak22byj1hrp";
    };
  };
  trytond-party-relationship = super.buildPythonPackage {
    name = "trytond-party-relationship-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-sql trytond-party trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/f4/3a/c8761d6e52b492e5d0b241567d716de2de2ce87a071a1c55c79877dbfac1/trytond_party_relationship-4.2.0.tar.gz";
      sha256 = "0lv64zxq6qk3df6rfqlgxzav96vnbm71ymq45isyribf4qa5cn2k";
    };
  };
  trytond-party-siret = super.buildPythonPackage {
    name = "trytond-party-siret-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-party trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/a8/4f/a0361c7e2a3b38ebf1dec27a65ff9f6b60455f807dd629377777c52e1e67/trytond_party_siret-4.2.0.tar.gz";
      sha256 = "0gb4k3mjn43lzb4zni3ppz3wd4kzp3haprdmfsl8qcgjjahdmc9g";
    };
  };
  trytond-party-vcarddav = super.buildPythonPackage {
    name = "trytond-party-vcarddav-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [vobject PyWebDAV python-sql trytond-party trytond-webdav trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/84/1f/707ac8d4b1d0ef2271f502bcba39838ba5e86d1d629f6aee29487a25ea36/trytond_party_vcarddav-4.2.0.tar.gz";
      sha256 = "1rs91sa9hrad6g17xf8riap207x12swhpzpfapy49dnr34kzjbgn";
    };
  };
  trytond-product = super.buildPythonPackage {
    name = "trytond-product-4.2.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-sql trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/bf/f7/4c75738492061ff304a5d2cb463883aa3c4c758bce63e0da50888681676f/trytond_product-4.2.1.tar.gz";
      sha256 = "1rimnn39isr0gy022l6k31rsv2543bz11aha02r3s9pdxpp4zhci";
    };
  };
  trytond-product-attribute = super.buildPythonPackage {
    name = "trytond-product-attribute-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-product trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/ce/7a/c390efaa54be8ef438a169e53626f44be71d3b514571cb4763406f32f62e/trytond_product_attribute-4.2.0.tar.gz";
      sha256 = "045xbis9aq4cj97zvbyrl0xxbicmb50gdpns3p66xik29cf0zphd";
    };
  };
  trytond-product-classification = super.buildPythonPackage {
    name = "trytond-product-classification-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-product trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/9e/31/1593625ab222a883f951d0d86b3397102d219fd55e46b5f7da6a4bd16b33/trytond_product_classification-4.2.0.tar.gz";
      sha256 = "0fx75syvim26y7d70hfcv1sl842y6ikdkghii7cvb6b7d0pkfzj5";
    };
  };
  trytond-product-classification-taxonomic = super.buildPythonPackage {
    name = "trytond-product-classification-taxonomic-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-product-classification trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/95/fe/f42514356041567742418d1fed544fc37cf478407f3c7c30d0df0f8c0e6c/trytond_product_classification_taxonomic-4.2.0.tar.gz";
      sha256 = "09vgjgkly7l47njk22wvmrz27hslzqn3knncnadzbr0kri4x27q7";
    };
  };
  trytond-product-cost-fifo = super.buildPythonPackage {
    name = "trytond-product-cost-fifo-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-product trytond-stock trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/ba/a3/8bf79a6da103f0e82221f95363547cfe52d2032ff8e8fa0215e456a42f52/trytond_product_cost_fifo-4.2.0.tar.gz";
      sha256 = "152hvi1hhniqp3jjjm4wdmhh6sg351p2knvnw1mh6ffjk0dav022";
    };
  };
  trytond-product-cost-history = super.buildPythonPackage {
    name = "trytond-product-cost-history-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-sql trytond-product trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/00/05/378d4e098781c252d8fec85b13c1172d48cf31ad6a363ce122bac61a0a7f/trytond_product_cost_history-4.2.0.tar.gz";
      sha256 = "02gf2v4d98iqvssmnc9y5ng294ih5a9l7bfrdplk3h7lgsj3ckhv";
    };
  };
  trytond-product-measurements = super.buildPythonPackage {
    name = "trytond-product-measurements-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-product trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/79/1b/3a1a6e2a8f6808e7fd5ee5718377503a8bc41a6a79f902ef028055987fbe/trytond_product_measurements-4.2.0.tar.gz";
      sha256 = "0n9lrwfnnyyds5n33wm4rf99ml0p6m9j9l75l8bqz6pzy3fq9hby";
    };
  };
  trytond-product-price-list = super.buildPythonPackage {
    name = "trytond-product-price-list-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [simpleeval python-sql trytond-company trytond-product trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/48/3d/e671549f78a8f6ef2d87d79732f8930ccb6a6298a78d561c459945d6010c/trytond_product_price_list-4.2.0.tar.gz";
      sha256 = "1w7p9nfnqph66jhci51qbjc7j9sljj59145ph7alf4663kanw1r6";
    };
  };
  trytond-production = super.buildPythonPackage {
    name = "trytond-production-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-sql trytond-company trytond-product trytond-stock trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/c0/86/c16cbcbbd7a096a2bfda299f0e327830edd97ce38f7827812de974d08f50/trytond_production-4.2.0.tar.gz";
      sha256 = "0bxzl8mjfs0z5yyz1fgn5y1ij5rnb0igfn3ny3hajd0ch475vl54";
    };
  };
  trytond-production-routing = super.buildPythonPackage {
    name = "trytond-production-routing-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-sql trytond-production trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/65/c3/2a70c613d45f7862c8119806d6534f53150df9e81f2e7a8191081ae9e3c1/trytond_production_routing-4.2.0.tar.gz";
      sha256 = "1z16ls8dx6gy61k8142w00ynly89m45rj6k3ywmkpv9p72fk6zhp";
    };
  };
  trytond-production-split = super.buildPythonPackage {
    name = "trytond-production-split-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-production trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/51/12/081e3f02e9af83cfeeb765d59e6cd1fa2cedc86e2e777ca250d14b42aa45/trytond_production_split-4.2.0.tar.gz";
      sha256 = "1lzsyl6g2gn3icncgg1kl9y0xm2dhddkbi5j9l3j7kzwn52bba7a";
    };
  };
  trytond-production-work = super.buildPythonPackage {
    name = "trytond-production-work-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-sql trytond-company trytond-production trytond-production-routing trytond-stock trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/5a/75/5146d9c4c64e6bce9e48ef1ee19f6d06de856a994584851929c24270da44/trytond_production_work-4.2.0.tar.gz";
      sha256 = "1wib39zi2z4gz59ri4ncvf3x0k546qvs2p9qli419k1bcnglpdyj";
    };
  };
  trytond-production-work-timesheet = super.buildPythonPackage {
    name = "trytond-production-work-timesheet-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-production-routing trytond-production-work trytond-timesheet trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/e4/a4/28e56bc6ef1860e46336272fb81a099caa882927076c08c106e2bfe12e1d/trytond_production_work_timesheet-4.2.0.tar.gz";
      sha256 = "0wlrpbmw9w3b7k3bh98wg6rpi5jarlpz34dcq4dwvi33y6fhyza2";
    };
  };
  trytond-project = super.buildPythonPackage {
    name = "trytond-project-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-sql trytond-company-work-time trytond-party trytond-timesheet trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/e0/60/a2cc5ec3714ccbe812352222a38bda4cf2340324db4e3fa74661e5b29af5/trytond_project-4.2.0.tar.gz";
      sha256 = "01qw98pda6qmkayirranzyp9msiabcrkip16vsk6gn80k1crzypb";
    };
  };
  trytond-project-invoice = super.buildPythonPackage {
    name = "trytond-project-invoice-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-sql trytond-project trytond-project-revenue trytond-timesheet trytond-account trytond-account-invoice trytond-product trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/1a/76/e8e021f9cd73e3023bc607dd012fa8170e3b48899b5a4b5bc233c207a6f9/trytond_project_invoice-4.2.0.tar.gz";
      sha256 = "09j8gqmqcy76kyz2hl53yw1l6m780y1lcndyyc52a6jypzj1ml8b";
    };
  };
  trytond-project-plan = super.buildPythonPackage {
    name = "trytond-project-plan-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-company trytond-project trytond-timesheet trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/99/42/838512938dfd8e64e835f5563c2e3b85e72693f95f92cf8efb3b2e598d18/trytond_project_plan-4.2.0.tar.gz";
      sha256 = "0p5a05pl7vp5n5imnsfvxcjp5cpns5f71d75m4bd9i8vm3qhhh5j";
    };
  };
  trytond-project-revenue = super.buildPythonPackage {
    name = "trytond-project-revenue-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-sql trytond-project trytond-timesheet trytond-timesheet-cost trytond-company trytond-product trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/03/78/a76e6084dc3d911c166dc9cd85ce051c3122e11ae381c2a33ec1c73ae339/trytond_project_revenue-4.2.0.tar.gz";
      sha256 = "1wwl0yl7wgs327fmskra7plxlgdhn6qd19zx05zmdsmxxqwpzdhl";
    };
  };
  trytond-purchase = super.buildPythonPackage {
    name = "trytond-purchase-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-sql trytond-account trytond-account-invoice trytond-account-invoice-stock trytond-account-product trytond-company trytond-currency trytond-party trytond-product trytond-stock trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/15/6e/4eeb5b47cc9f5c791ded5f924a89014c2cac57685c72a1b696ead7e8d3d3/trytond_purchase-4.2.0.tar.gz";
      sha256 = "0mvzrq3mmmj4nhwyprvqqlfs9b1sdnq5n58aps66048nv70cysc7";
    };
  };
  trytond-purchase-invoice-line-standalone = super.buildPythonPackage {
    name = "trytond-purchase-invoice-line-standalone-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-sql trytond-account-invoice-line-standalone trytond-purchase trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/d5/6c/af4dfad05d7f6d4ef320a7a476e01ae890d398dadfef98db23c7d2f6a04b/trytond_purchase_invoice_line_standalone-4.2.0.tar.gz";
      sha256 = "0mpa2qpm96jqib895wfln9gk4ngrgdxcymfkmdbv7924vx58lzgb";
    };
  };
  trytond-purchase-request = super.buildPythonPackage {
    name = "trytond-purchase-request-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-purchase trytond-product trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/cc/f1/d056c0eb05e75ef5c8413d396c4af77a0bdde7b946f9b4212ee332de6100/trytond_purchase_request-4.2.0.tar.gz";
      sha256 = "11hck68izjk0msmszdks421c0bilqd28vxq9zzva7q77dj771sli";
    };
  };
  trytond-purchase-shipment-cost = super.buildPythonPackage {
    name = "trytond-purchase-shipment-cost-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-carrier trytond-currency trytond-stock trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/da/81/151f5d849b4b6fe6be7257d1581759a895f676cae86be21c7257fd300df2/trytond_purchase_shipment_cost-4.2.0.tar.gz";
      sha256 = "12ga9qab3sqpx2avr867a2l018d409n8z6ib03gxr5q7y73xkyz3";
    };
  };
  trytond-sale = super.buildPythonPackage {
    name = "trytond-sale-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-sql trytond-account trytond-account-invoice trytond-account-invoice-stock trytond-account-product trytond-company trytond-currency trytond-party trytond-product trytond-stock trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/99/23/38986792cb97cf7c85511879be3147df8b355af8922d7e53aa11f31b256a/trytond_sale-4.2.0.tar.gz";
      sha256 = "00j0swrmhb8vgrph00s1y9gkshyl1vwh23mgl62nk6qggllwmwgz";
    };
  };
  trytond-sale-complaint = super.buildPythonPackage {
    name = "trytond-sale-complaint-4.2.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-account-invoice trytond-company trytond-party trytond-sale trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/fd/e6/8677429e2e8e258f0f16b041de8fc846598a952df06b9537d4d13f041484/trytond_sale_complaint-4.2.1.tar.gz";
      sha256 = "0cqkfyyyv9pyz9v0wqfwk1h0izcmlww2p4g19w4z4r8pksz3c6fx";
    };
  };
  trytond-sale-credit-limit = super.buildPythonPackage {
    name = "trytond-sale-credit-limit-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-account-credit-limit trytond-sale trytond-currency trytond-account-invoice trytond-company trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/32/12/78245ca3f8fc11d6bc5c7a886034c5937b3499dd478aa7624a7544fa5ed8/trytond_sale_credit_limit-4.2.0.tar.gz";
      sha256 = "0jr3dh504iv6j5avy3s4y663rgx70xi4a4ag2q8zcg2q327sq6z4";
    };
  };
  trytond-sale-extra = super.buildPythonPackage {
    name = "trytond-sale-extra-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-sql trytond-company trytond-product trytond-product-price-list trytond-sale trytond-sale-price-list trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/f9/f8/2344584af9d35aa3b2e91a90f386150af56a10e1f625495751f4213705a7/trytond_sale_extra-4.2.0.tar.gz";
      sha256 = "0ds0b3kycp6pvlrb8q5nqrxjczlrq5njvrl9531cnkbbwm164ack";
    };
  };
  trytond-sale-invoice-grouping = super.buildPythonPackage {
    name = "trytond-sale-invoice-grouping-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-party trytond-account-invoice trytond-sale trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/32/07/e7770d331442c314c6ef5d29c8d71566111484e5ee4eb04695371007cebd/trytond_sale_invoice_grouping-4.2.0.tar.gz";
      sha256 = "1k361q5jwmsqdk79zwgz0qmcb2l2q0mblkfvxsw14hnalp32qda2";
    };
  };
  trytond-sale-opportunity = super.buildPythonPackage {
    name = "trytond-sale-opportunity-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-sql trytond-account trytond-account-invoice trytond-company trytond-currency trytond-party trytond-product trytond-sale trytond-stock trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/ff/32/dee72fcd29d30a7d4fdeeae57dbf20f0fb79a3790df9c1edef68fced69a2/trytond_sale_opportunity-4.2.0.tar.gz";
      sha256 = "0k5f2vkzarr0n79vb826xnvjxk7b215i5fhvpd5r2868sff44kpx";
    };
  };
  trytond-sale-price-list = super.buildPythonPackage {
    name = "trytond-sale-price-list-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-party trytond-product-price-list trytond-sale trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/c3/59/1d1eb6086b9af9bc936647763b1d92242b2ad7c28ba695ee85afc7342d21/trytond_sale_price_list-4.2.0.tar.gz";
      sha256 = "08r3w9d4zcfc4hgc110sicrjr53gv3ifcrd6zjlccas3sfy6b6xf";
    };
  };
  trytond-sale-promotion = super.buildPythonPackage {
    name = "trytond-sale-promotion-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [simpleeval trytond-company trytond-product trytond-product-price-list trytond-sale trytond-sale-price-list trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/66/29/4e8db822e78f06703c975f50ce17da1822fd30713bff8fc5f9266952672b/trytond_sale_promotion-4.2.0.tar.gz";
      sha256 = "04j1sky0991sl6m8bcmjf0d6pz3xk2m1mxdfhxc1hvnb4yjrlsmw";
    };
  };
  trytond-sale-shipment-cost = super.buildPythonPackage {
    name = "trytond-sale-shipment-cost-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-account-invoice trytond-carrier trytond-currency trytond-sale trytond-stock trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/22/4f/3ffdcc92681741eee217f2364bd3ab1fa142fd15203631d25a28911bf6ff/trytond_sale_shipment_cost-4.2.0.tar.gz";
      sha256 = "0g58jnzmycqz8g4rjg35ns2ikq25ww5g0b7gfxzsrzh4i100g6zd";
    };
  };
  trytond-sale-shipment-grouping = super.buildPythonPackage {
    name = "trytond-sale-shipment-grouping-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-party trytond-stock trytond-sale trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/0f/c9/4e5b849a201112789f2363bc5223ce57cf42d8e0517828fd68c5aab3d810/trytond_sale_shipment_grouping-4.2.0.tar.gz";
      sha256 = "1hw1kj2486mn0abrfn94nf4hc02mm6nna0mmylhbdr6d3z01jzwi";
    };
  };
  trytond-sale-stock-quantity = super.buildPythonPackage {
    name = "trytond-sale-stock-quantity-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-product trytond-sale trytond-stock trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/59/7d/f14476ca8563beb04598278d199da39728643ec2303d485fe95e38f009c5/trytond_sale_stock_quantity-4.2.0.tar.gz";
      sha256 = "01jxw575c6hfsph3fwp0qmdnj6glbm3a85b9zi3zy4a3q3d3fkkh";
    };
  };
  trytond-sale-supply = super.buildPythonPackage {
    name = "trytond-sale-supply-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-purchase trytond-purchase-request trytond-sale trytond-stock trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/59/62/fd9e7d5bda970c7aae0f4f6d5c83c49b7a69c57ed0da7c4fffb9b17a31e4/trytond_sale_supply-4.2.0.tar.gz";
      sha256 = "1kqd9sr5rygyjc26wkgvzjjbp6arxma36mn8djdhdz90531zhyw2";
    };
  };
  trytond-sale-supply-drop-shipment = super.buildPythonPackage {
    name = "trytond-sale-supply-drop-shipment-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-company trytond-purchase trytond-purchase-request trytond-sale trytond-sale-supply trytond-stock trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/d0/46/e55b2ddb3899de2b45e43234179bf4f476d4cbdcf6735119a7d9c6f26092/trytond_sale_supply_drop_shipment-4.2.0.tar.gz";
      sha256 = "0zl9k823rna78mfhc07rcv1ajnvnp2a1kaxs6k1sxb0isxcipda8";
    };
  };
  trytond-stock = super.buildPythonPackage {
    name = "trytond-stock-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-sql trytond-company trytond-currency trytond-party trytond-product trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/c5/be/2b8670ec6136eaf9e74955ef69a5a9dbc9f41aacf10e11815254f7802623/trytond_stock-4.2.0.tar.gz";
      sha256 = "1n8zqsg6kdsvhh7ki72fvsj64iz1v70rd884vk48d7sd3pjbcvx6";
    };
  };
  trytond-stock-forecast = super.buildPythonPackage {
    name = "trytond-stock-forecast-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-dateutil python-sql trytond-company trytond-product trytond-stock trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/4a/54/1d19acb12aaf137422bfd2aacd29d74b3c98d23e518d5877f31af5bdb149/trytond_stock_forecast-4.2.0.tar.gz";
      sha256 = "10k7sd94b9zskpmbss5dmdb0l1x09k0rk6mwfn4sxblrc59m1alp";
    };
  };
  trytond-stock-inventory-location = super.buildPythonPackage {
    name = "trytond-stock-inventory-location-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-company trytond-product trytond-stock trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/ee/f7/499f32d985e69140488279a8a751cbeecd698263ea156031d19cb13a8f06/trytond_stock_inventory_location-4.2.0.tar.gz";
      sha256 = "0vamw8hhbwwp3hjjv2v6s90bwj1lml61yni37blfsb8zli70j164";
    };
  };
  trytond-stock-location-sequence = super.buildPythonPackage {
    name = "trytond-stock-location-sequence-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-sql trytond-stock trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/d0/bf/f56658f825be1bd79c5c3e54634db413c49a5ae5596c8a703974afb821c3/trytond_stock_location_sequence-4.2.0.tar.gz";
      sha256 = "0dw0gjgd9qclqqnsmjz67m7qqw42w13xdfwz28zd979c2dpgfi8f";
    };
  };
  trytond-stock-lot = super.buildPythonPackage {
    name = "trytond-stock-lot-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-product trytond-stock trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/2b/09/b34efc5b4cd7d759c81d91aa6b97ced74082b89fc3a7f89b51b7c3e5cefd/trytond_stock_lot-4.2.0.tar.gz";
      sha256 = "03267ml2as2fyaz5w2cjg3xkaimrxys16mlf3mrxglmrgi2zmfks";
    };
  };
  trytond-stock-lot-sled = super.buildPythonPackage {
    name = "trytond-stock-lot-sled-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-sql trytond-product trytond-stock trytond-stock-lot trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/2f/6e/f02f5de63844004efc5afc729179948d1f3f57095cdc37013038efaa1e6a/trytond_stock_lot_sled-4.2.0.tar.gz";
      sha256 = "03vcf4qyj07n25q0in7ll10fjn4gjl1wlb7j1qdmmp4bcnmi7hfm";
    };
  };
  trytond-stock-package = super.buildPythonPackage {
    name = "trytond-stock-package-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-stock trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/c6/fb/051e182bed03500177fccda5b1b42616e3ac0aabde81726f10bec417eda5/trytond_stock_package-4.2.0.tar.gz";
      sha256 = "1q65as40d4q0n93zw4xph3l8qyc5950h9va0rwja7gq080sqln16";
    };
  };
  trytond-stock-package-shipping = super.buildPythonPackage {
    name = "trytond-stock-package-shipping-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-carrier trytond-product trytond-stock trytond-stock-package trytond-sale-shipment-cost trytond-product-measurements trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/29/99/d0a06e8904fccb85a7f2e7bf56e3c178586b39404b0eb1c03e829a286262/trytond_stock_package_shipping-4.2.0.tar.gz";
      sha256 = "0f2h6fpzs183h4p1kvhlxq0q5a2paf2yfb9n96qc8wca989sra8k";
    };
  };
  trytond-stock-package-shipping-dpd = super.buildPythonPackage {
    name = "trytond-stock-package-shipping-dpd-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [zeep PyPDF2 trytond-party trytond-product trytond-stock trytond-stock-package trytond-stock-package-shipping trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/0b/fa/0d9d1fd028868c906abd79199d1119dc0706fe0a9c67ff281c5d8b0d6714/trytond_stock_package_shipping_dpd-4.2.0.tar.gz";
      sha256 = "1hn0alam75cnrf7blybpc5wwalh54np84ihxzvkm18v29k0klhaq";
    };
  };
  trytond-stock-package-shipping-ups = super.buildPythonPackage {
    name = "trytond-stock-package-shipping-ups-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [requests trytond-party trytond-product trytond-stock trytond-stock-package trytond-stock-package-shipping trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/b9/9a/5ab5af73061d690f9e6619a9dc6a1a3d5e7810c29e9d23ef5c0f07eb6be5/trytond_stock_package_shipping_ups-4.2.0.tar.gz";
      sha256 = "1pbjnfywm4vph3m2z2pf4rv0nhwwd9a6s77is2x1v5k751qxs1bz";
    };
  };
  trytond-stock-product-location = super.buildPythonPackage {
    name = "trytond-stock-product-location-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-sql trytond-product trytond-stock trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/23/54/f365bcf859b55d7054265f53658ae19d35d2d0d27461ca7a720f7ac3a8ef/trytond_stock_product_location-4.2.0.tar.gz";
      sha256 = "1p9r46z3xs25skz9zd2vcccqi50y41wjdj6jmiqricnmxsb9j6f6";
    };
  };
  trytond-stock-split = super.buildPythonPackage {
    name = "trytond-stock-split-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-stock trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/1b/b8/98a1b2284a759db1e6564cb602fd6fa4b9a9a86682cb2e5729d218555295/trytond_stock_split-4.2.0.tar.gz";
      sha256 = "0n8xjj8khif34z7n4s3ca3rk2ps3lb3vy2mnc9c7x4n5zjjxjv3p";
    };
  };
  trytond-stock-supply = super.buildPythonPackage {
    name = "trytond-stock-supply-4.2.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-sql trytond-account trytond-party trytond-product trytond-purchase trytond-purchase-request trytond-stock trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/37/31/85a22fca42888456c322e3d7252a0fed2cfd2ce0dac7fb3e764fbe8a3b49/trytond_stock_supply-4.2.1.tar.gz";
      sha256 = "1mv79kmj7s3zggpsv9jg7znsjx5pgzd69ip722x61q7c395jkr90";
    };
  };
  trytond-stock-supply-day = super.buildPythonPackage {
    name = "trytond-stock-supply-day-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-purchase trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/6e/81/39f129534738679e8f142e30b93de3bfb79295b3566d73d6e5ce182b5195/trytond_stock_supply_day-4.2.0.tar.gz";
      sha256 = "0yrxv7h43fcyl0y74nd1izwx8wv6wvhcmcf2fm875jxyhs9cznxq";
    };
  };
  trytond-stock-supply-forecast = super.buildPythonPackage {
    name = "trytond-stock-supply-forecast-4.2.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-stock-supply trytond-stock-forecast trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/12/e6/5141a77aa63ef3f4cdfa1c3aa5a8fbe0a81faa98411cfd56a066da00525a/trytond_stock_supply_forecast-4.2.1.tar.gz";
      sha256 = "012ry7k87a2d1p4dcng4wc0d8a0xnb67l6vfc6szn5favcbh2y1i";
    };
  };
  trytond-stock-supply-production = super.buildPythonPackage {
    name = "trytond-stock-supply-production-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-product trytond-production trytond-stock trytond-stock-supply trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/9f/36/2dfafa6aeed90a2c062cd81782abc6fad096a9159bcb7f055ceda45899c3/trytond_stock_supply_production-4.2.0.tar.gz";
      sha256 = "042wbwdbm5dk3yha00lvwbfnbc32k9b2hb9z81fkf2x3hl3s9jwx";
    };
  };
  trytond-timesheet = super.buildPythonPackage {
    name = "trytond-timesheet-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-sql trytond-company trytond-company-work-time trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/af/92/144094a04bac5e54d2d03b860d1240c72db382d23139631b06ba9b2dfa9a/trytond_timesheet-4.2.0.tar.gz";
      sha256 = "1i3mzzz6cy2h6vh55gnqcfcvz99ln7vh6xpaawxsnigrlscl5085";
    };
  };
  trytond-timesheet-cost = super.buildPythonPackage {
    name = "trytond-timesheet-cost-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [python-sql trytond-company trytond-party trytond-timesheet trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/2b/20/e9188e19bb058660c1e83de305259826b879ae128232fae258423f2bb897/trytond_timesheet_cost-4.2.0.tar.gz";
      sha256 = "1j0kwdwdilw0dir3m2qzanlnz3mkc86kd158jbn8cjp8g23nmfn8";
    };
  };
  trytond-web-user = super.buildPythonPackage {
    name = "trytond-web-user-4.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [trytond-party trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/2b/77/68e0d18607833c58e8e9badd968bd5a430103d486b2e1e2c282d0d258f9b/trytond_web_user-4.2.0.tar.gz";
      sha256 = "1nzknvsvmj04zpq5f8pb3rs9plfyr2yi0bxsx3abb76rwpjjn9wq";
    };
  };
  trytond-webdav = super.buildPythonPackage {
    name = "trytond-webdav-4.2.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [PyWebDAV trytond];
    src = fetchurl {
      url = "https://pypi.python.org/packages/38/db/afb798e9d8192155d76bab669497e32d08a256753963dffa8144d9064b04/trytond_webdav-4.2.1.tar.gz";
      sha256 = "0bhhh0485ddwx83w38j3y010v17laijq06pbj32s1ydz9xg3hirk";
    };
  };

### Test requirements


}
